
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Upload static files for Pages
    uses: actions/upload-pages-artifact@v1
    with:
      path: ./

      steps:
  - name: Deploy to GitHub Pages
    uses: actions/deploy-pages@v1
